# From https://github.com/pi-hole/docker-pi-hole
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: {{ pihole_image }}
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8000:80/tcp"
      - "8001:443/tcp"
    environment:
      TZ: 'Europe/Paris'
      FTLCONF_webserver_api_password: {{ pihole_password }}
      PIHOLE_BASE: /opt/pihole-storage
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - '/etc/pihole:/etc/pihole'
    restart: unless-stopped
