services:
  rproxy:
    image: nginx:latest
    network_mode: "host"  # Needed to be able to redirect to any host port
    container_name: rproxy
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/conf.d/:/etc/nginx/conf.d/:ro
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
