---
##########################################
# squid.conf generation
# Define Local network CIDR
# These are default squid config
# For more security please only your network
local_network:
  - "0.0.0.1-0.255.255.255  # RFC 1122 this network (LAN)"
  - "10.0.0.0/8             # RFC 1918 local private network (LAN)"
  - "100.64.0.0/10          # RFC 6598 shared address space (CGN)"
  - "169.254.0.0/16         # RFC 3927 link-local (directly plugged) machines"
  - "172.16.0.0/12          # RFC 1918 local private network (LAN)"
  - "192.168.0.0/16         # RFC 1918 local private network (LAN)"
  - "fc00::/7               # RFC 4193 local private network range"
  - "fe80::/10              # RFC 4291 link-local (directly plugged) machines"
# Define Local server to connect
extra_server:
  - name: "Example"
    ip: "192.168.0.1/32"
    ports:
      - 8008
##########################################
# podman-squid.service generation
squid_image: "ubuntu/squid:5.2-22.04_beta"
