---
# TODO: Remove whend podman >=4.4
# Not investing to much, the goal is to have podman quadlet
- name: Install dependencies, pls have docker repo installed
  ansible.builtin.package:
    name: "docker-ce,docker-compose-plugin,logrotate,net-tools,dnsutils,ufw"
    state: "present"

- name: Allow necessary ports
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items:
    - port: "ssh"
      proto: "tcp"
    - port: "8000"
      proto: "tcp"
    - port: "8001"
      proto: "tcp"
    - port: "53"
      proto: "udp"
    - port: "53"
      proto: "tcp"

- name: Start firwall
  community.general.ufw:
    state: reloaded
    policy: allow

# TODO: Uncomment when podman >=4.4
# - name: Install dependencies
#   ansible.builtin.package:
#     name: "podman,logrotate"
#     state: "present"

- name: Init PIHole directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: 999
    state: "directory"
  with_items:
    - "/etc/pihole/"
    - "/etc/pihole/hosts/"
    - "/var/log/pihole/"
    - "/etc/dnsmasq.d/"

- name: add pihole dns entries
  ansible.builtin.template:
    src: "pihole.list"
    dest: "/etc/pihole/hosts/pihole.list"
    owner: 0
    group: 0
    mode: 644

- name: add extra_servers dns entries
  ansible.builtin.template:
    src: "extraservers.list"
    dest: "/etc/pihole/hosts/extraservers.list"
    owner: 0
    group: 0
    mode: 644

- name: Update rproxy
  ansible.builtin.template:
    src: "pihole.conf"
    dest: "/etc/nginx/conf.d/pihole.conf"

- name: Restart rproxy
  ansible.builtin.command:
    chdir:  "/root/Application/rproxy/"
    cmd: "docker compose restart"

# TODO: Implement QUADLET when podman >=4.4

# TODO: Remove whend podman >=4.4
# Not investing to much, the goal is to have podman quadlet
- name: Init squid directories
  ansible.builtin.file:
    path: "/root/Application/Pihole/"
    state: "directory"

- name: Setup docker-compose
  ansible.builtin.template:
    src: "docker-compose.yaml"
    dest: "/root/Application/Pihole/docker-compose.yaml"
    owner: 0
    group: 0
    mode: '700'

- name: Update Image
  ansible.builtin.command:
    chdir:  "/root/Application/Pihole/"
    cmd: "docker compose pull"

- name: STOP Daemon
  ansible.builtin.command:
    chdir:  "/root/Application/Pihole/"
    cmd: "docker compose down"

- name: START Daemon
  ansible.builtin.command:
    chdir:  "/root/Application/Pihole/"
    cmd: "docker compose up -d"

- name: Test server up and running
  ansible.builtin.command:
    cmd: "nslookup pi.hole {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  retries: 3
  delay: 5
