---
# TODO: Remove whend podman >=4.4
# Not investing to much, the goal is to have podman quadlet
- name: Install dependencies, pls have docker repo installed
  ansible.builtin.package:
    name: "docker-ce,docker-compose-plugin,logrotate"
    state: "present"

# TODO: Uncomment when podman >=4.4
# - name: Install dependencies
#   ansible.builtin.package:
#     name: "podman,logrotate"
#     state: "present"

- name: Init PIHole directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: 999
    state: "directory"
  with_items:
    - "/etc/pihole/"
    - "/var/log/pihole/"
    - "/etc/dnsmasq.d/"

# TODO: Implement QUADLET when podman >=4.4

# TODO: Remove whend podman >=4.4
# Not investing to much, the goal is to have podman quadlet
- name: Init squid directories
  ansible.builtin.file:
    path: "/root/Application/Pihole/"
    state: "directory"

- name: Setup docker-compose
  ansible.builtin.template:
    src: "docker-compose.yaml"
    dest: "/root/Application/Pihole/docker-compose.yaml"

- name: Update Image
  ansible.builtin.command:
    chdir:  "/root/Application/Pihole/"
    cmd: "docker compose pull"

- name: STOP Daemon
  ansible.builtin.command:
    chdir:  "/root/Application/Pihole/"
    cmd: "docker compose down"

- name: START Daemon
  ansible.builtin.command:
    chdir:  "/root/Application/Pihole/"
    cmd: "docker compose up -d"
